[versions]
netty = "4.1.115.Final"
kotlin = "2.1.10"
okio = "3.10.2"
ktor = "3.0.0"

[libraries]
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "24.0.0" }

squareup-okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

ktor-network = { group = "io.ktor", name = "ktor-network", version.ref = "ktor" }

netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }
netty-resolver = { group = "io.netty", name = "netty-resolver", version.ref = "netty" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
